version: "3.5"
services:
  cuda_steps_parser_service:
    image: cuda_steps_parser
    environment:
      - STEPS_PARSER_PORT=8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility,compute]
