FROM nvidia/cuda:11.2.0-devel-ubuntu20.04

RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl unzip python3 python3-pip nvidia-modprobe
RUN pip3 install --upgrade pip

RUN pip3 install wheel setuptools
RUN pip3 install cython

RUN pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

ADD ./.env $HOME/.env
RUN chmod +x ./.env
RUN ./.env

ADD ./requirements_service.txt $HOME/requirements.txt
RUN pip3 install -r requirements.txt

RUN pip3 install transformers==3.1.0
RUN pip3 install mlflow stanza pyconll

# env var empty
#VOLUME $STEPS_PARSER_MODEL_DIR

ADD ./src/ $HOME/src/
ADD ./gpu/start_gpu_service.sh $HOME/start_service.sh

# not needed, could be used to install via conda instead of pip
#ADD ./environment.yml $HOME/environment.yml

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN chmod +x ./start_service.sh
CMD ./start_service.sh
