FROM nvidia/cuda:11.3.0-devel-ubuntu20.04
ADD ./requirements_service.txt $HOME/requirements.txt
ADD ./.env $HOME/.env
RUN chmod +x ./.env
RUN ./.env
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y curl
RUN apt-get install unzip
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install -r requirements.txt
RUN pip3 install transformers==3.1.0
RUN pip3 install mlflow
RUN pip3 install stanza
RUN pip3 install pyconll
RUN apt-get install -y nvidia-modprobe

ADD ./$STEPS_PARSER_MODEL_DIR/ $HOME/$STEPS_PARSER_MODEL_DIR/
ADD ./src/ $HOME/src/
ADD ./gpu/start_gpu_service.sh $HOME/start_service.sh
ADD ./environment.yml $HOME/environment.yml
RUN chmod +x ./start_service.sh
CMD ./start_service.sh
